pmem/pmemkv-java

src/test/java/io/pmem/pmemkv/tests/KVEngineTest.java
These changes are required by pmem/pmemkv#274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/16)
=> Adjust tests to the new pmemkv config

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/13)
=> Update installation information

README.md
tiny change
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/17)
=> Update installation tips

.gitignore, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/GetAllBufferCallback.java, src/main/java/io/pmem/pmemkv/GetAllByteArrayCallback.java, src/main/java/io/pmem/pmemkv/GetAllStringCallback.java, src/main/java/io/pmem/pmemkv/GetKeysBuffersCallback.java, src/main/java/io/pmem/pmemkv/GetKeysByteArraysCallback.java, src/main/java/io/pmem/pmemkv/GetKeysStringsCallback.java, src/main/java/io/pmem/pmemkv/internal/GetAllBufferJNICallback.java, src/main/java/io/pmem/pmemkv/internal/GetKeysBuffersJNICallback.java, src/test/java/io/pmem/pmemkv/tests/DatabaseTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/20)
=> Adjust to all pmemkv API changes

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/22)
=> Update README - Example

ChangeLog, pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/23)
=> Add ChangeLog with version 0.8

README.md, examples/BasicExample.java, examples/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/25)
=> Move example from the pmemkv-tools

pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/27)
=> Update to 0.9

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/31)
=> Fix repo name in CONTRIBUTING.md

.travis.yml, utils/docker/images/Dockerfile.fedora-31, utils/docker/images/Dockerfile.ubuntu-19.10, utils/docker/images/install-dependencies.sh, utils/docker/images/install-libpmemobj-cpp.sh, utils/docker/images/install-pmdk.sh, utils/docker/images/prepare-pmemkv.sh, utils/docker/run-build.sh
- add Fedora image (v. 31)
- update jdk version
- set JAVA_* variables once, in image
- minor cleanup and pmemkv version update
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/32)
=> Update travis files

pom.xml, utils/docker/images/install-libpmemobj-cpp.sh, utils/docker/images/install-pmdk.sh, utils/docker/images/prepare-pmemkv.sh, utils/docker/run-build.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/34)
=> Update dependencies and fix run-build.sh

utils/docker/images/install-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/37)
=> Update JAVA version in dependency installation script

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md, .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/45)
=> add issues' templates to use on GitHub

examples/BasicExample.java, src/main/java/io/pmem/pmemkv/Database.java, src/test/java/io/pmem/pmemkv/tests/DatabaseTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/47)
=> Api changes part1

src/io_pmem_pmemkv_Database.cpp
This PR is next part of bigger initiative of the code refactoring for 1.0 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/48)
=> Direct access

.github/ISSUE_TEMPLATE/question.md, NOTICES.md, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/50)
=> use https instead of http in .md files

src/io_pmem_pmemkv_Database.cpp, src/main/java/io/pmem/pmemkv/ConfigParsingErrorException.java, src/main/java/io/pmem/pmemkv/ConfigTypeErrorException.java, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/DatabaseException.java, src/main/java/io/pmem/pmemkv/DefragErrorException.java, src/main/java/io/pmem/pmemkv/InvalidArgumentException.java, src/main/java/io/pmem/pmemkv/NotFoundException.java, src/main/java/io/pmem/pmemkv/NotSupportedException.java, src/main/java/io/pmem/pmemkv/OutOfMemoryException.java, src/main/java/io/pmem/pmemkv/StoppedByCallbackException.java, src/main/java/io/pmem/pmemkv/TransactionScopeErrorException.java, src/main/java/io/pmem/pmemkv/UnknownErrorException.java, src/main/java/io/pmem/pmemkv/WrongEngineNameException.java, src/test/java/io/pmem/pmemkv/tests/DatabaseTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/57)
=> Exceptions

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/59)
=> update README for 1.0.0 release

src/main/cpp/io_pmem_pmemkv_Database.cpp, src/main/cpp/pom.xml, src/main/java/io/pmem/pmemkv/BuilderException.java, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/DatabaseException.java, src/main/java/io/pmem/pmemkv/InvalidArgumentException.java, src/main/java/io/pmem/pmemkv/NotFoundException.java, src/main/java/io/pmem/pmemkv/NotSupportedException.java, src/main/java/io/pmem/pmemkv/OutOfMemoryException.java, src/main/java/io/pmem/pmemkv/StoppedByCallbackException.java, src/main/java/io/pmem/pmemkv/TransactionScopeException.java, src/main/java/io/pmem/pmemkv/WrongEngineNameException.java, src/main/pom.xml, src/test/java/io/pmem/pmemkv/tests/CmapTest.java, src/test/java/io/pmem/pmemkv/tests/DatabaseTest.java, src/test/java/io/pmem/pmemkv/tests/ExceptionTest.java, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.ubuntu-20.04
They really didn't want us to find these fails (all "show warning" options are by default "false" 😃 )
@karczex, is this what you wanted? ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/65)
=> enable compilation failure on warnings

RELEASE_STEPS.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/68)
=> add RELEASE_STEPS.md

src/main/java/io/pmem/pmemkv/BuilderException.java, src/main/java/io/pmem/pmemkv/Database.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/71)
=> Remove redundant package level imports

README.md
waiting for the content of the gh-pages,; it's under review:
code: https://github.com/lukaszstolarczuk/pmemkv-java/tree/gh-pages
preview: https://lukaszstolarczuk.github.io/pmemkv-java/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/70)
=> update README with docs links and minor fixes

README.md, src/main/java/io/pmem/pmemkv/BuilderException.java, src/main/java/io/pmem/pmemkv/ByteBufferConverter.java, src/main/java/io/pmem/pmemkv/Converter.java, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/DatabaseException.java, src/main/java/io/pmem/pmemkv/InvalidArgumentException.java, src/main/java/io/pmem/pmemkv/KeyCallback.java, src/main/java/io/pmem/pmemkv/KeyValueCallback.java, src/main/java/io/pmem/pmemkv/NotFoundException.java, src/main/java/io/pmem/pmemkv/NotSupportedException.java, src/main/java/io/pmem/pmemkv/OutOfMemoryException.java, src/main/java/io/pmem/pmemkv/StoppedByCallbackException.java, src/main/java/io/pmem/pmemkv/TransactionScopeException.java, src/main/java/io/pmem/pmemkv/ValueCallback.java, src/main/java/io/pmem/pmemkv/WrongEngineNameException.java, src/main/pom.xml
preview: https://karczex.github.io/pmemkv-java/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/62)
=> Documentation

.github/workflows/gha.yml, .travis.yml, utils/docker/run-build.sh, utils/docker/run-doc-update.sh, utils/docker/valid-branches.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/72)
=> Add auto doc gen

index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/74)
=> add releases' statuses table on gh-pages

utils/docker/images/install-dependencies.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/77)
=> Bump java version in dependencies script in CI

src/main/java/io/pmem/pmemkv/BuilderException.java, src/main/java/io/pmem/pmemkv/Converter.java, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/DatabaseException.java, src/main/java/io/pmem/pmemkv/InvalidArgumentException.java, src/main/java/io/pmem/pmemkv/KeyCallback.java, src/main/java/io/pmem/pmemkv/KeyValueCallback.java, src/main/java/io/pmem/pmemkv/NotFoundException.java, src/main/java/io/pmem/pmemkv/NotSupportedException.java, src/main/java/io/pmem/pmemkv/OutOfMemoryException.java, src/main/java/io/pmem/pmemkv/StoppedByCallbackException.java, src/main/java/io/pmem/pmemkv/TransactionScopeException.java, src/main/java/io/pmem/pmemkv/ValueCallback.java, src/main/java/io/pmem/pmemkv/WrongEngineNameException.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/75)
=> minor fixes in javadocs' comments

DEBUGGING.md, README.md
File with development tips and tricks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/54)
=> Add DEBUGGING.md

README.md
* Add missing information of jni dependencies
* Remove development and testing dependencies - In fact there is many,
more dependencies than those two, and all are managed by mvn
automatically
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/78)
=> Fix dependencies in readme

.github/workflows/gha.yml, .travis.yml, src/main/java/io/pmem/pmemkv/BuilderException.java, src/main/java/io/pmem/pmemkv/Converter.java, src/main/java/io/pmem/pmemkv/Database.java, src/main/java/io/pmem/pmemkv/DatabaseException.java, src/main/java/io/pmem/pmemkv/InvalidArgumentException.java, src/main/java/io/pmem/pmemkv/KeyCallback.java, src/main/java/io/pmem/pmemkv/KeyValueCallback.java, src/main/java/io/pmem/pmemkv/NotFoundException.java, src/main/java/io/pmem/pmemkv/NotSupportedException.java, src/main/java/io/pmem/pmemkv/OutOfMemoryException.java, src/main/java/io/pmem/pmemkv/StoppedByCallbackException.java, src/main/java/io/pmem/pmemkv/TransactionScopeException.java, src/main/java/io/pmem/pmemkv/ValueCallback.java, src/main/java/io/pmem/pmemkv/WrongEngineNameException.java, utils/docker/images/install-dependencies.sh, utils/docker/run-build.sh, utils/docker/run-doc-update.sh, utils/docker/valid-branches.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/79)
=> Merge changes from stable 1.0 into master

utils/docker/build.sh, utils/docker/images/build-image.sh, utils/docker/images/push-image.sh, utils/docker/pull-or-rebuild-image.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/73)
=> bump docker images tag/versioning used on dockerhub

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature.md, .github/ISSUE_TEMPLATE/question.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/83)
=> align issues' labels to recent update

examples/PicturesExample.java, examples/README.md, utils/docker/run-build.sh
Complex example with mixed types of key (String) and value
(BufferedImage)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/85)
=> Add PicturesExample

README.md, src/main/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/90)
=> Merge changes from stable-1.0 into master

NOTICES.md, src/main/pom.xml, src/test/java/io/pmem/pmemkv/tests/CmapTest.java, src/test/java/io/pmem/pmemkv/tests/DatabaseTest.java, src/test/java/io/pmem/pmemkv/tests/ExceptionTest.java
junit serves all needed functionalities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/96)
=> Tests: remove oleaster-matcher dependency

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/100)
=> readme: wrong package names

examples/PicturesExample/src/main/java/PicturesExample.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/117)
=> example: fix minor output issue

examples/PicturesExample/src/main/java/PicturesExample.java
- remove dummy code
- add 'Override' annotation where is needed
- move example logic to dedicated class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/118)
=> PicturesExample: small refactor

.github/workflows/gha.yml, utils/docker/build.sh, utils/docker/run-build.sh
and cleanup build.sh a little.
It was necessary to pass some extra variables in build.sh (which I missed with the last CI/utils update). BTW, I introduced separate job in GHA workflow as in our other repos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/121)
=> CI: fix auto docs update

pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java
Add throws clause for proper documentation generation and also for user information about possible exception
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/109)
=> [java part] add throws clause for methods

pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java
I will also look at the reflection mechanism to extend test: exceptionsHierarchy()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/122)
=> refactor: cleanup unused variables and imports

jni-binding/pom.xml
This PR do not need any description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/127)
=> [jni] remove flags not related with linker options

examples/ByteBufferExample/pom.xml, examples/MixedTypesExample/pom.xml, examples/PicturesExample/pom.xml, examples/StringExample/pom.xml, examples/pom.xml, jni-binding/pom.xml, pmemkv-binding/pom.xml, pom.xml
part of it is required for pushing to mvn central
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/120)
=> Update pom files

.gitignore, DEBUGGING.md, README.md, examples/README.md, pmemkv-binding/pom.xml, pom.xml, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.ubuntu-20.04
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/119)
=> Minor cleanups

ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/107)
=> Changelog: update changelog for pmemkv-java 1.0.1 release

DEBUGGING.md, README.md, examples/README.md, utils/docker/prepare-for-build.sh, utils/docker/run-build.sh, utils/docker/run-doc-update.sh
\+ minor cleanups in run-*.sh scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/141)
=> Fix hardcoded paths in CI

pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, utils/docker/images/install-dependencies.sh
and bump pmemkv/pmemkv-java dependencies versions.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/143)
=> Fix javadoc warnings

.github/workflows/gha.yml, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.ubuntu-20.04, utils/docker/images/install-pmdk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/147)
=> Docker images

README.md, pmemkv-binding/pom.xml, pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java
fixes: #88
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/148)
=> tests: make test path configurable by maven property

jni-binding/io_pmem_pmemkv_Database.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/151)
=> JNI: Change C API to C++

.github/workflows/maven.yml, README.md, examples/pom.xml, utils/docker/build.sh, utils/docker/images/Dockerfile.ubuntu-20.04_clean, utils/docker/images/install-dependencies.sh, utils/docker/prepare-for-build.sh, utils/docker/run-build.sh, utils/docker/run-maven-example.sh
// CI job execution preview: https://github.com/lukaszstolarczuk/pmemkv-java/runs/2638515771 (see this precise line: [link](https://github.com/lukaszstolarczuk/pmemkv-java/runs/2638515771#step:5:379))
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/153)
=> add CI job using maven

ChangeLog
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/154)
=> add ChangeLog for 1.1 release

examples/ByteBufferExample/src/main/java/ByteBufferExample.java, examples/MixedTypesExample/src/main/java/MixedTypesExample.java, examples/PicturesExample/src/main/java/PicturesExample.java, examples/StringExample/src/main/java/StringExample.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/Converter.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/KeyCallback.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/KeyValueCallback.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/ValueCallback.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/162)
=> Update examples and docs

pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java
This PR introduces straightforward description
of what user will get when exception will be thrown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/164)
=> [Readme] Change description of DatabaseException

.github/workflows/gha.yml, jni-binding/common.cpp, jni-binding/common.h, jni-binding/io_pmem_pmemkv_Database.cpp, jni-binding/io_pmem_pmemkv_Database_WriteIterator.cpp, jni-binding/libpmemkv_jni.map, jni-binding/pom.xml, pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseWriteIteratorTest.java
Intention of this PR is to provide C++ iterators from PMEMKV as Java API.
TODO:
***---------------------------------------------------------------------------------------------------------------***
***Historical description, will be moved to another PR as extension of this change.***
***---------------------------------------------------------------------------------------------------------------***
Intention of this PR is to introduce iterators in Java API.
Implementation will cover following interfaces: 
- `Map.Entry<E>` - [documentation](https://docs.oracle.com/javase/8/docs/api/java/util/Map.Entry.html)
- `Iterable<E>` - [documentation](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html)
- `Iterator<E>` - [documentation](https://docs.oracle.com/javase/8/docs/api/java/uti …
=> Java: Iterator API implementation

.github/workflows/maven.yml
Fix for last maven job fail in CI:
https://github.com/pmem/pmemkv-java/runs/2651996141?check_suite_focus=true#step:3:1580
Preview of the job:
https://github.com/lukaszstolarczuk/pmemkv-java/runs/2791343123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/155)
=> CI: add missing variables in maven job

LICENSE, index.md
and recent blog post link.
Preview on my fork:
https://lukaszstolarczuk.github.io/pmemkv-java/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/170)
=> [gh-pages] update index.md and LICENSE with new release(s)

README.md
This PR updates pmemkv-java in Maven artifact snippet and changes pmemkv version in README.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/165)
=> [Readme] Update readme to the pmemkv 1.4 and change snippet to be more generic

ChangeLog, README.md, jni-binding/io_pmem_pmemkv_Database_Builder.cpp, jni-binding/libpmemkv_jni.map, jni-binding/pom.xml, pmemkv-binding/src/main/java/io/pmem/pmemkv/Database.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/CmapTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/DatabaseTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/ExceptionTest.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java
given as String or InputStream.
Fixes #161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/171)
=> enable specifying config params from JSON Object

LICENSE, index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/176)
=> [gh-pages] add links for 1.2 branch documentation

README.md, RELEASE_STEPS.md
with latest release's information and updated process of releasing new packages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/177)
=> update README.md and RELEASE_STEPS.md

.github/workflows/maven.yml, README.md, RELEASE_STEPS.md, utils/docker/images/Dockerfile.ubuntu-21.04_clean, utils/docker/images/install-dependencies.sh, utils/docker/images/install-libpmemobj-cpp.sh, utils/docker/images/install-pmdk.sh, utils/docker/images/prepare-pmemkv.sh, utils/docker/run-build.sh, utils/docker/run-maven-example.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/180)
=> Merge stable-1.2 into master

.github/workflows/gha.yml, utils/docker/images/Dockerfile.fedora-32, utils/docker/images/Dockerfile.fedora-33, utils/docker/images/Dockerfile.fedora-34, utils/docker/images/install-dependencies.sh, utils/docker/images/install-libpmemobj-cpp.sh, utils/docker/images/prepare-pmemkv.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/182)
=> CI: Update Fedora 32 (to 34) and enable builds with pmemkv 1.5

README.md, RELEASE_STEPS.md, jni-binding/io_pmem_pmemkv_Database.cpp, pmemkv-binding/src/main/java/io/pmem/pmemkv/ByteBufferConverter.java, pmemkv-binding/src/main/java/io/pmem/pmemkv/WrongEngineNameException.java, pmemkv-binding/src/test/java/io/pmem/pmemkv/TestUtils.java, utils/docker/run-doc-update.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/pmemkv-java/186)
=> Minor updates
